#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec  1 16:09:58 2019

@author: jeremiah
"""

#%% importings
from keras.preprocessing.image import ImageDataGenerator
import os
import cv2
import random
import numpy as np

#%%
path = "/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/BelgiumTSC_v2/Training/no_entry_for_all_drivers"

img_size = 64
training_data = []

for img in os.listdir(path):
    
    img_array = cv2.imread(os.path.join(path, img))
    new_array = cv2.resize(img_array, (img_size, img_size))
    training_data.append(new_array)

training_data = np.array(training_data, "float32")

print("Data readed!\nLength of the dataset: ", len(training_data))

y = [1 for i in range(len(training_data))]

y = np.array(y, "float32").reshape(len(y), 1)
#%%
rotation = 45
shift = 0.2
flip = True
zoom = 0.2
datagen = ImageDataGenerator(rotation_range = rotation, width_shift_range=shift, height_shift_range=shift, 
                             horizontal_flip=flip, vertical_flip=flip, zoom_range=zoom)

datagen.fit(training_data)

dir = "/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/BelgiumTSC_v2/Training/no_entry_for_all_drivers_v2"

for X, y in datagen.flow(training_data, y, batch_size=3, save_to_dir=dir, save_prefix="aug", save_format="png"):
    break
