#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 29 14:31:38 2019

@author: jeremiah
"""
#%%

import tensorflow as tf
import pathlib
import numpy as np
import cv2
import os
import sys

sys.path.insert(1, '/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/CNN-for-traffic-sign-classification/src')

import build_model, get_data

#%%
img_size = 256

model = build_model.build_cnn_model(n_classes = 3, input_shape = (img_size, img_size, 3), filter_size = 3, gray_scale = False, drop_prob_conv=0.25, drop_prob_fully=0.5)
#%%
model.load_weights("/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/CNN-for-traffic-sign-classification/trained_models/weights_aug.hdf5")

#%%

export_dir = "/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/CNN-for-traffic-sign-classification/tflite/saved_model"
#%%
tf.saved_model.save(model, export_dir)

#%%
converter = tf.lite.TFLiteConverter.from_saved_model(export_dir)
#converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_model = converter.convert()

#%%
tflite_model_file = pathlib.Path("/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/CNN-for-traffic-sign-classification/tflite/model.tflite")
tflite_model_file.write_bytes(tflite_model)



#%%
datadir = "/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/ufpa_dataset_aug/Training"

categories = []

for folder in os.listdir(datadir):
    categories.append(folder)
    
img_size = 128

img_array = cv2.imread("/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/teste/5.png")
img_array = cv2.resize(img_array, (img_size, img_size))
img_array = np.array(img_array, "float32").reshape(1, img_size, img_size, 3)
#%%
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()


interpreter.set_tensor(input_details[0]["index"], img_array)
interpreter.invoke()
tflite_results = interpreter.get_tensor(output_details[0]["index"])

idx = tf.argmax(tflite_results, axis=1)
print(max(max(tflite_results)))
print(categories[int(idx)])


#%%

for i in range(len(categories)):
    categories[i] = categories[i].replace("_", " ")
cat = ""

for i in categories:
    cat += i+"\n"
#%%
path = "/media/jeremiah/7E9BF5A34D96B6A4/2019.4/PE3/CNN-for-traffic-sign-classification/tflite/labels.txt"
with open(path, "w") as file:
    file.write(cat)
    















